[connections.gsheets]
spreadsheet_id = "https://docs.google.com/spreadsheets/d/1IAgqGL9nlMSvtm4lZMUUz-SF8c4l3rYokfvp9WSq5EU/edit?usp=sharing"
type = "service_account"
project_id = "valinsa-project"
private_key_id = "8e761480705a9b4d03a8d5be731de924e57d5efd"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDt2v33QXWR4GLw
/tZoFERzSql9JQZaPSkJc3Gpm0Pa29GTaTihNQmCrMqxrOVGKS7Z/3OxvYZhkDzb
J8Z62JPgVCyeKQzNdnq/C6x6+is2x3y/yeD6CvFvP2jQ/pheTrbs69jQHJti17Kw
ScDLpVFVpWf4ZM1K6V0AXgGHAhOzGs0AubFRN7FyNBEPoTxZK3uS4dC3aZ0cpGO4
XSwXGuS3sjHyJNCihQVKfmEjFN43NXVyCaavOCvmVzBM/APWfUGdYyybOJ46ADAi
FmOyfdnAY8Cgmp5BwhTHHcej/RcJBz8DwaHoj2OGaAcVzNHQfXj8oEnLySfInEG5
UYmGPFbjAgMBAAECggEACefY3nc8wjp/ZFyjPpUO1LkDSKbwwMlTRYV9R6b5CHWn
ILsnv0RKL8WqcK6BTeQL2Mr+snmbeGyysXMn8kMaxXjmnXTwMjkA8PviJFekJ7/f
E3hWL5OibROi9dvkfz5KoqCf2EBDaGEQnAQ2TJox7PMv2p8NaFVCU5rr+AdqHUdS
kKztU6bvqS6RvYYbIO9mvXDtJ5LJ8JA+UBvYzgKuxG9aebxkD6Fl0GEm85D8fF2H
qTU+JHZi1i9zCM0Wz9ul+jZhsXQJMrV4FxQ1E8K1cz6J1n4HIKrSVraeQMIiqdJy
SGDCIL0gdV9lhZ6NIEIv820TywdFDbY3eCg2bQiZgQKBgQD8Tt1E3UlsGH8HNWQD
80LTuL364hgDef9bIyiQqIO445/KjcTGG1t4K9Me64Cbn33rQIEmknFXN+US6icl
r69llxImx/mGDnouU6PWRqdI8bExTKM1WzvO4Pvd8tzjhfk4ax2piEuCegjVZVEm
m7514WAXzfB4kPl87Nf3IQVG8QKBgQDxVf0gfIkJL1o4XdFbQUdbfGAfEnqackqY
PrX1rUtPrbq2lCE3jEcuKCVBhj+WwcxsLBIg5/OLF4hi5YI9G/F0bLU0nQ7SgPCr
9pBtaJtMV0PnhkDrNiFxJrMEo3UsAyNmwOADvcF0AsF4gPP4WvREvLu0K5TkxsYs
4IO1q7dDEwKBgQDxZ7+8MQIcI//+dK4iPXF2Q++6CPOy99pEaApbBnEpyNjNpAFf
DzPgcgYJMokV3W9MVKZ9smYxbjCGfXVBUKxARmA+rN1oz5dFlg9PaMCMQXwpUEtk
NMuvsIIsJUAFjd0bhxmVaOvehkbHbq5Lg36jKSWZARkRMp0TU0V7laOH8QKBgGe9
2w33+sBkBphsW+6qZQ5CrN8uhl2V+9LuQjHVyKX7vGN30b+bIY4J29oK55LaxBFL
8I8MpniIKSy6E/5I4MZ3ZH21dgWvP8XsO7GMYhWy/ZGs+IMjxcRqKlI4IcpFnxYw
mxuAmoRQGvK+HCIKly5lIxsUEPE3MUFhUbzqj+DZAoGBANvWtbIs274Rfzxe0+gg
06foNTl/KkO2lGFUuDyrL2Nvt47VDtn2ilR8pLz0kisdjshAMWfjfezTBIebmWYd
o4DMC8/lWUfn6i02CPpI/Rpt88TAVSN1y6xdUrfSIkHCo0bGDSSydprK7RpR3PLa
4nbCVn6ouha/KH6/j09R28zf
-----END PRIVATE KEY-----"""
client_email = "valinsa-bot@valinsa-project.iam.gserviceaccount.com"
client_id = "100364829258939426092"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/web/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/valinsa-bot%40valinsa-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"